name: newstream
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://newstream:newstream@dev-db:5432/newstream?schema=public
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./.env:/app/.env
    depends_on:
      dev-db:
        condition: service_healthy
      redis:
        condition: service_started

  dev-db:
    image: postgres:13
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: newstream
      POSTGRES_PASSWORD: newstream
      POSTGRES_DB: newstream
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U newstream']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - '6380:6379'
    command: redis-server
    volumes:
      - redis-data:/data

volumes:
  redis-data:
