version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: newstream-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: newstream
      POSTGRES_PASSWORD: newstream
      POSTGRES_DB: newstream
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U newstream"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: newstream-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
