name: Deploy Docker to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Prepare EB Docker context
        run: |
          # Copy all necessary backend files to root for Docker build
          rm -rf source
          mkdir -p source
          cp backend/Dockerfile source/
          cp backend/package.json source/
          cp backend/package-lock.json source/
          mkdir -p source/prisma
          cp -r backend/prisma/* source/prisma/
          mkdir -p source/scripts
          cp -r backend/scripts/* source/scripts/
          mkdir -p source/src
          cp -r backend/src/* source/src/

      - name: Zip source bundle
        run: zip -r app.zip ./source -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: docker-${{ github.run_number }}
          use_existing_version_if_available: true
          deployment_package: app.zip